### ISSUE TITLE
Benchmark speed

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/DiversityOptimization#2]
Goal: determine performance of [MinDivLp.py](https://github.com/KoslickiLab/DiversityOptimization/blob/master/PythonCode/src/MinDivLP.py) as a function of:

- [x] support size of vector to be reconstructed
- [x] number of rows in sensing matrix
- [x] number of columns in sensing matrix

Approach: using the [data](https://www.dropbox.com/sh/6pb7955rlzdx5sc/AAAqf-1RGVSBLdL3F2h-Qc14a?dl=0) (or modifications thereof, or randomly generated "similar looking" sensing matrices), in pseudo-code:
```python
for num_rows in <some range>:
    for num_columns in <some range>:
        form the sensing matrix A
        for support sizes in <some range>:
            for N random x vectors:
                form y
                time MinDivLP.py
                store timing results
average over N
report performance (plot or tabular form): min, max, median, mean, std dev of time
```

**Comment by cmcolbert** [comment]
Results from benchmarking speed:
[results_N=20.xlsx](https://github.com/KoslickiLab/DiversityOptimization/files/4706678/results_N.20.xlsx)
Log-log graphs of results (support size vs. mean time over varying column counts and large_k values):
![logSvslogt-k4](https://user-images.githubusercontent.com/61798566/83340049-5b14b080-a299-11ea-99a1-5c586682494e.png)
![logSvslogt-k6](https://user-images.githubusercontent.com/61798566/83340051-5bad4700-a299-11ea-9491-1ae55cd37caa.png)
![logSvslogt-k8](https://user-images.githubusercontent.com/61798566/83340052-5bad4700-a299-11ea-9d5d-b1750fe41daa.png)
![logSvslogt-k10](https://user-images.githubusercontent.com/61798566/83340053-5bad4700-a299-11ea-8bca-80f04b2a72e7.png)
![logSvslogt-k12](https://user-images.githubusercontent.com/61798566/83340054-5c45dd80-a299-11ea-9f2a-857661e70ad7.png)
![logSvslogt-k13](https://user-images.githubusercontent.com/61798566/83340055-5c45dd80-a299-11ea-87b1-dfc340ce5fee.png)

**Comment by dkoslicki** [comment]
@cmcolbert is this log base 10 or log base e, or...?

**Comment by cmcolbert** [comment]
@dkoslicki This is log base e.
